### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by kennykimjr** [aomkirby123/nextjs-preactX#1]
This is just a direct escalation as I'm trying to find out how to make nextjs work with Preact X. As I noted [here](https://github.com/zeit/next-plugins/issues/483), I was unable to build your repository. I cloned from the master branch and started with "yarn run build" and came up with the error of not being able to find React:

```
$ next build
The module 'react' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install --save react'
The module 'react-dom' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install --save react-dom'
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'react'

```

**Comment by aomkirby123** [comment]
As commit of ef1637032bd4ea671a6ad6c056db2599bae04f4e, I update a trick that add react as dev-depencies to trick Next.js, but we actually use Preact.

**Comment by aomkirby123** [comment]
I’ll leave this issue opened, as I am still not sure if we could build without React.js.

**Comment by kennykimjr** [comment]
Hi @aomkirby123 

So I went out and tried the repo, and it worked great! Except a few things I noted:

- The scripts broke on my end because SET is not a valid keyword. I assume you used this on windows since that was where the SET keyword is but I think a lot of developers also develop on macOS as well as Linux. There's the [cross-env](https://github.com/kentcdodds/cross-env) for setting environment variables in scripts if you want it to work on both windows and linux/unix shells.   
- This will actually break with the beta.3 if you try using hooks. Beta.2 works for hooks for now but if you upgrade to beta.3, beware if you try to use the new preact hooks API.

Overall this worked really great!
